Update system apps | December 11, 2024

diff --git a/noxdg/bin/global/update_app_list b/noxdg/bin/global/update_app_list
--- a/noxdg/bin/global/update_app_list
+++ b/noxdg/bin/global/update_app_list
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -x
+
 sync_system_apps() {
   sudo pacman -Qen | sort >"$1/installed_apps.txt"
 }
@@ -27,15 +29,40 @@ sync_aur_apps() {
   paru -Qm | sort >"$1/installed_aur_apps.txt"
 }
 
-main() {
-  DOTFILES_PATH="/home/bryant/Documents/github/dotfiles/apps"
+commit_changes_to_git() {
+  FORMATTED_DATE=$(date "+%B %d, %Y")
 
-  sync_system_apps $DOTFILES_PATH
-  sync_python_apps $DOTFILES_PATH
-  sync_rust_apps $DOTFILES_PATH
-  sync_go_apps $DOTFILES_PATH
-  sync_flatpak_apps $DOTFILES_PATH
-  sync_aur_apps $DOTFILES_PATH
+  if [ -z "$1" ]; then
+    echo "Error: Please provide a directory path"
+    return 1
+  fi
+
+  cd "$1" || {
+    echo "Error: Could not change to directory $1"
+    return 1
+  }
+
+  git add .
+
+  name=$(git config --get user.name)
+  email=$(git config --get user.email)
+  author="${name} <${email}>"
+
+  sudo git commit --author "$author" "$FORMATTED_DATE" "$@"
+
+}
+
+main() {
+  dot_path="/home/bryant/Documents/github/dotfiles/apps"
+
+  sync_system_apps $dot_path
+  sync_python_apps $dot_path
+  sync_rust_apps $dot_path
+  sync_go_apps $dot_path
+  sync_flatpak_apps $dot_path
+  sync_aur_apps $dot_path
+
+  commit_changes_to_git "$dot_path"
 }
 
 main
